[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
escrow = "7qE8jLFrYQZ8Mwgw6ju4CZP4z9rCAvV8meSr3WTCmacN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/merdanaslan/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
